	common: &common
    access_key_id: AKIAIWWQF5REKTC4ZYGQ
    secret_access_key: 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

development:
    <<: *common
    bucket: meritize

test:
    <<: *common
    bucket: meritize

production:
    access_key_id: AKIAIGK7VSI6A2XYSYSA
    secret_access_key: 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
    bucket: meritizephotos
